import:
  - ~/dotfiles/config/alacritty/themes/gruvbox.yml
  # - ~/dotfiles/config/alacritty/themes/everforest.yml

env:
  TERM: xterm-256color

window:
  opacity: 1.0
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 2
    y: 2
  dynamic_padding: false
  decorations: full
  startup_mode: Maximized
  dynamic_title: true

scrolling:
  history: 1000
  multiplier: 3

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
  size: 10
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: true

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false

draw_bold_text_with_bright_colors: true

bell:
  animation: EaseOutExpo
  duration: 0
  color: "0xffffff"

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: false

hints:
  enabled:
    - regex: "(http:|https:)\
        [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: xdg-open
      post_processing: true
      mouse:
        enabled: true
        mods: None

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  style:
    shape: Block
    blinking: Off
  unfocused_hollow: true

live_config_reload: true

winpty_backend: false

alt_send_esc: true

key_bindings: []
