set -gx fish_color_autosuggestion 747369
set -gx fish_color_cancel normal
set -gx fish_color_command 99cc99
set -gx fish_color_comment ffcc66
set -gx fish_color_cwd 008000
set -gx fish_color_cwd_root 800000
set -gx fish_color_end dfbf8e
set -gx fish_color_error f2777a
set -gx fish_color_escape 66cccc
set -gx fish_color_history_current normal
set -gx fish_color_host normal
set -gx fish_color_host_remote yellow
set -gx fish_color_match 6699cc
set -gx fish_color_normal normal
set -gx fish_color_operator 6699cc
set -gx fish_color_param dfbf8e
set -gx fish_color_quote ffcc66
set -gx fish_color_redirection d3d0c8
set -gx fish_color_search_match \x2d\x2dbackground\x3dblack
set -gx fish_color_selection c0c0c0
set -gx fish_color_status red
set -gx fish_color_user 00ff00
set -gx fish_color_valid_path normal
set -gx fish_pager_color_completion normal
set -gx fish_pager_color_description B3A06D\x1eyellow
set -gx fish_pager_color_prefix white\x1e\x2d\x2dbold\x1e\x2d\x2dunderline
set -gx fish_pager_color_progress brwhite\x1e\x2d\x2dbackground\x3dcyan
