[terminal]
vt = 1

[default_session]
command = "tuigreet --remember --time --sessions /usr/share/wayland-sessions --xsessions /usr/share/xsessions --xsession-wrapper /usr/share/vanhtuan0409/scripts/xsession-wrapper.sh"
user = "greeter"
