add_newline = false
scan_timeout = 10

format = """
[┌](bold #689d6a) $directory$git_branch$git_status$kubernetes
[└>](bold #689d6a)$status """

[directory]
style = "bold #d79921"

[git_branch]
symbol = ""
style = "bold #689d6a"

[git_status]
format = '([\[$all_status\]]($style) )'
style = "bold #b8bb26"

[kubernetes]
disabled = false
format = "via [$symbol$context/$namespace]($style)"
symbol = ""
style = "bold #d79921"

[status]
disabled = false
format = "[\\($status\\)]($style)"
