alias vim="nvim"
alias zshconfig="vim $HOME/.zshrc"
alias zshalias="vim $DOTFILES/zsh/lib/alias.zsh"
alias zshreload="source $HOME/.zshrc"
alias vimconfig="vim $HOME/.vimrc"
alias vimbundles="vim $HOME/.vimrc.bundles"
alias vimkeybindings="vim $HOME/.vimrc.keybindings"
alias tmuxconfig="vim $HOME/.tmux.conf"
alias kscontext="kubectl config use-context"
alias gitdiscard="git reset --hard && git clean -fd"
alias epoch="date +%s"
alias g="goto"
alias r="ranger"
alias publicip="dig +short myip.opendns.com @resolver1.opendns.com"

# alias for notes https://github.com/pimterry/notes
alias n="notes"
