alias vim="nvim"
alias kscontext="kubectl config use-context"
alias gitdiscard="git reset --hard && git clean -fd"
alias epoch="date +%s"
alias cat="bat"
alias dig="dog"
alias ls="exa"
alias g="goto"
alias r="bash $DOTFILES/scripts/rand.sh"
alias grep="rg"
alias publicip="dig +short myip.opendns.com @resolver1.opendns.com"
# alias for notes https://github.com/pimterry/notes
alias n="notes"
alias open="xdg-open"
alias nnn="PAGER=less nnn"
alias tf="terraform"
