version: 2
root-markers:
  - .git/

tools:
  goimports: &goimports
    format-command: 'goimports'
    format-stdin: true

  rustfmt: &rustfmt
    format-command: 'rustfmt'
    format-stdin: true

languages:
  go:
    - <<: *goimports
  rust:
    - <<: *rustfmt

